# Setup
title: 韩俊辉
description: 🌃
url: https://jhh0207.github.io
avatar: /images/tx.jpg
paginate: 5
permalink: pretty
cover_image: /images/bg.jpg

# Gems
plugins:
  - jekyll-gist
  - jekyll-paginate
  - jekyll-seo-tag
  - jekyll-feed
  - jekyll-sitemap

# Optimize Jekyll
exclude:
  - .editorconfig
  - .git
  - .jekyll-cache
  - Gemfile
  - Gemfile.lock
  - LICENSE.md
  - README.md
  - scripts/
  - not-pure-poole.gemspec

# Optimize Jekyl SEO Tag
twitter:
  username: 
  card: 
logo: /images/tx.jpg
social:
  name: 韩俊辉
  links:
    - https://github.com/jhh0207
google_site_verification: 
lang: en

sass:
  sass_dir: _sass
  style: :compressed

# Options

# Replace this value and uncomment to enable Google Analytics tracking
# google_analytics: 

# Replace this value and uncomment to enable Disqus
# disqus: xxxxxx

# Specify the author for blog posts
author:
  name: 韩俊辉
  url: /about
  email: 3047285021@qq.com
